In [4]:
import pandas as pd

In [24]:
import numpy as np

In [34]:
import math 

In [5]:
data=pd.read_excel('realestate.xlsx')


In [6]:
data

LIST.PRICE  SQFT                  HOME.TYPE  BEDS  BATHS  LOT.SIZE  \
0       895.000  3040  Single Family Residential     4   2.50   54886.0   
1       659.000  2920  Single Family Residential     3   2.75   38754.0   
2      1840.000  3845  Single Family Residential     4   3.25   46609.0   
3       335.000   928                      Condo     2   1.00       NaN   
4       299.000  1044                  Townhouse     2   1.50       NaN   
..          ...   ...                        ...   ...    ...       ...   
309     600.000  1414                      Condo     2   2.25       NaN   
310     529.000  1202                      Condo     2   1.75       NaN   
311     489.900  1538                  Townhouse     2   2.00       NaN   
312     150.090   736                      Condo     1   1.00       NaN   
313     118.671   752                      Condo     1   1.00       NaN   

     YEAR.BUILT  DAYS.ON.MARKET  PARKING.TYPE    ZIP  
0          1961             349             1  80303  
1          1966              81             1  80303  
2          2005              19             1  80303  
3          1982              31             1  80305  
4          1972              24             1  80305  
..          ...             ...           ...    ...  
309        2008              13             1  80304  
310        2008              12             1  80304  
311        2003              33             1  80304  
312        2005              12             1  80304  
313        2011              10             1  80304  

[314 rows x 10 columns]

In [7]:
data.isna().sum()

LIST.PRICE         0
SQFT               0
HOME.TYPE          0
BEDS               0
BATHS              0
LOT.SIZE          94
YEAR.BUILT         0
DAYS.ON.MARKET     0
PARKING.TYPE       0
ZIP                0
dtype: int64

In [9]:
data.mean()

LIST.PRICE          967.761602
SQFT               2559.585987
BEDS                  3.044586
BATHS                 2.484076
LOT.SIZE          25296.900000
YEAR.BUILT         1982.238854
DAYS.ON.MARKET       74.318471
PARKING.TYPE          0.901274
ZIP               80303.028662
dtype: float64

In [11]:
data=data.fillna(data.mean())

In [12]:
data

LIST.PRICE  SQFT                  HOME.TYPE  BEDS  BATHS  LOT.SIZE  \
0       895.000  3040  Single Family Residential     4   2.50   54886.0   
1       659.000  2920  Single Family Residential     3   2.75   38754.0   
2      1840.000  3845  Single Family Residential     4   3.25   46609.0   
3       335.000   928                      Condo     2   1.00   25296.9   
4       299.000  1044                  Townhouse     2   1.50   25296.9   
..          ...   ...                        ...   ...    ...       ...   
309     600.000  1414                      Condo     2   2.25   25296.9   
310     529.000  1202                      Condo     2   1.75   25296.9   
311     489.900  1538                  Townhouse     2   2.00   25296.9   
312     150.090   736                      Condo     1   1.00   25296.9   
313     118.671   752                      Condo     1   1.00   25296.9   

     YEAR.BUILT  DAYS.ON.MARKET  PARKING.TYPE    ZIP  
0          1961             349             1  80303  
1          1966              81             1  80303  
2          2005              19             1  80303  
3          1982              31             1  80305  
4          1972              24             1  80305  
..          ...             ...           ...    ...  
309        2008              13             1  80304  
310        2008              12             1  80304  
311        2003              33             1  80304  
312        2005              12             1  80304  
313        2011              10             1  80304  

[314 rows x 10 columns]

In [13]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [14]:
le.fit(data["HOME.TYPE"])

LabelEncoder()

In [16]:
data["HOME.TYPE"]=le.transform(data["HOME.TYPE"])

In [17]:
data

LIST.PRICE  SQFT  HOME.TYPE  BEDS  BATHS  LOT.SIZE  YEAR.BUILT  \
0       895.000  3040          1     4   2.50   54886.0        1961   
1       659.000  2920          1     3   2.75   38754.0        1966   
2      1840.000  3845          1     4   3.25   46609.0        2005   
3       335.000   928          0     2   1.00   25296.9        1982   
4       299.000  1044          2     2   1.50   25296.9        1972   
..          ...   ...        ...   ...    ...       ...         ...   
309     600.000  1414          0     2   2.25   25296.9        2008   
310     529.000  1202          0     2   1.75   25296.9        2008   
311     489.900  1538          2     2   2.00   25296.9        2003   
312     150.090   736          0     1   1.00   25296.9        2005   
313     118.671   752          0     1   1.00   25296.9        2011   

     DAYS.ON.MARKET  PARKING.TYPE    ZIP  
0               349             1  80303  
1                81             1  80303  
2                19             1  80303  
3                31             1  80305  
4                24             1  80305  
..              ...           ...    ...  
309              13             1  80304  
310              12             1  80304  
311              33             1  80304  
312              12             1  80304  
313              10             1  80304  

[314 rows x 10 columns]

In [18]:
data_matrix=data.values

In [19]:
data_matrix

array([[8.95000e+02, 3.04000e+03, 1.00000e+00, ..., 3.49000e+02,
        1.00000e+00, 8.03030e+04],
       [6.59000e+02, 2.92000e+03, 1.00000e+00, ..., 8.10000e+01,
        1.00000e+00, 8.03030e+04],
       [1.84000e+03, 3.84500e+03, 1.00000e+00, ..., 1.90000e+01,
        1.00000e+00, 8.03030e+04],
       ...,
       [4.89900e+02, 1.53800e+03, 2.00000e+00, ..., 3.30000e+01,
        1.00000e+00, 8.03040e+04],
       [1.50090e+02, 7.36000e+02, 0.00000e+00, ..., 1.20000e+01,
        1.00000e+00, 8.03040e+04],
       [1.18671e+02, 7.52000e+02, 0.00000e+00, ..., 1.00000e+01,
        1.00000e+00, 8.03040e+04]])

In [22]:
X=data_matrix[0:,1:]

In [23]:
X

array([[3.0400e+03, 1.0000e+00, 4.0000e+00, ..., 3.4900e+02, 1.0000e+00,
        8.0303e+04],
       [2.9200e+03, 1.0000e+00, 3.0000e+00, ..., 8.1000e+01, 1.0000e+00,
        8.0303e+04],
       [3.8450e+03, 1.0000e+00, 4.0000e+00, ..., 1.9000e+01, 1.0000e+00,
        8.0303e+04],
       ...,
       [1.5380e+03, 2.0000e+00, 2.0000e+00, ..., 3.3000e+01, 1.0000e+00,
        8.0304e+04],
       [7.3600e+02, 0.0000e+00, 1.0000e+00, ..., 1.2000e+01, 1.0000e+00,
        8.0304e+04],
       [7.5200e+02, 0.0000e+00, 1.0000e+00, ..., 1.0000e+01, 1.0000e+00,
        8.0304e+04]])

In [25]:
Y=data_matrix[0:,0]

In [26]:
Y

array([ 895.   ,  659.   , 1840.   ,  335.   ,  299.   , 6499.   ,
       1500.   , 2790.   ,  479.9  , 1487.5  , 2795.   ,  140.   ,
        425.   , 1965.   ,  410.   , 1900.   ,  899.9  ,  609.9  ,
        545.   ,  699.9  ,  589.   ,  700.   ,  415.   ,  329.9  ,
        975.   ,  999.9  , 1849.   , 3250.   , 3875.   ,  345.   ,
        339.   ,  349.   ,  162.9  ,  255.   ,  824.   ,  629.5  ,
        699.9  ,  679.   ,  375.   ,  485.   ,  172.9  ,  229.9  ,
        998.   , 1199.9  ,  949.   ,  998.   ,  479.   ,  485.   ,
       1850.   ,  519.   , 1095.   ,  675.   ,  899.   ,  565.   ,
       1700.   ,  339.9  ,  469.9  ,  559.9  , 1895.   ,  162.4  ,
       1050.   ,  575.7  ,  710.   ,  225.   ,  524.9  ,  205.   ,
        174.9  , 2195.   ,  139.999,  439.9  ,  184.9  ,  678.   ,
        329.   ,  149.9  , 1175.   , 1650.   ,  257.5  ,  995.   ,
       2195.   ,  550.   ,  559.9  ,  181.999,  269.   , 1389.   ,
        287.9  ,  240.   ,  642.5  ,  128.9  ,  138.5  ,  173.

In [27]:
scaler = preprocessing.StandardScaler().fit(X)

In [28]:
X=scaler.transform(X)

In [29]:
X

array([[ 0.27440612,  0.47948371,  0.69974379, ...,  2.49836432,
         0.33096924, -0.02476109],
       [ 0.20586371,  0.47948371, -0.03265471, ...,  0.06077181,
         0.33096924, -0.02476109],
       [ 0.73421145,  0.47948371,  0.69974379, ..., -0.50314885,
         0.33096924, -0.02476109],
       ...,
       [-0.58351638,  2.15234912, -0.76505321, ..., -0.37581193,
         0.33096924,  0.83912578],
       [-1.04160815, -1.19338169, -1.4974517 , ..., -0.56681731,
         0.33096924,  0.83912578],
       [-1.03246916, -1.19338169, -1.4974517 , ..., -0.5850083 ,
         0.33096924,  0.83912578]])

In [37]:
X.shape[0]*0.8

251.20000000000002

In [36]:
math.floor(X.shape[0]*0.8)

251

In [38]:
X_train=X[0:math.floor(X.shape[0]*0.8)]

In [39]:
X_train.shape

(251, 9)

In [40]:
X_test=X[math.floor(X.shape[0]*0.8):]
Y_train=Y[0:math.floor(X.shape[0]*0.8)]
Y_test=Y[math.floor(X.shape[0]*0.8):]

In [41]:
from sklearn.linear_model import LinearRegression

In [43]:
reg = LinearRegression().fit(X_train, Y_train)

In [44]:
 reg.score(X_train, Y_train)

0.6896553063250539

In [46]:
Y_pred=reg.predict(X_test)

In [47]:
Y_pred

array([1606.50410648,  832.52947676, 1376.30441981, 3032.08997042,
       2190.23338108,  274.92965231, 1630.24119901, 2508.35748378,
        719.88759432, 1029.78066519, 2042.81891465, 1581.64694199,
        864.41831822, 5493.11366348, 1886.54336843, 1614.22403175,
       2035.74960257, 3295.9649757 ,  353.07110695, 1838.89066983,
        521.96687852,  843.89774943,  693.00873261,  310.28894969,
        297.60891162,  310.6293876 , 2023.4233902 , 1959.59556586,
        330.39009229, 1662.58541033, 2012.23618437,  811.06410505,
       2254.45028368, 1599.46848644, 1571.97453718,  304.71876444,
       1971.6598201 ,  463.42135247, 2300.03864102, 1403.39988118,
        228.44906112,  105.7901116 ,  609.0921711 ,  313.12795216,
       2674.3999458 ,  814.68483191, 1771.02285667,  403.923945  ,
        267.36236895, 2551.98879433, 2744.41783566, 3795.44421899,
        198.29213704, 1386.7656043 ,  789.39389321,  323.95020015,
        940.77678765,  230.3555134 ,  485.7034747 ,  381.24217

In [48]:
Y_test

array([1100.   ,  719.   , 1125.   , 2995.   , 2825.   ,  574.9  ,
       1289.5  , 2295.   ,  520.   ,  335.638, 1150.   ,  775.   ,
        625.   , 7500.   , 1250.   ,  829.   ,  995.   , 3250.   ,
        339.   ,  775.   ,  530.   ,  670.   ,  619.9  , 1250.   ,
        485.   , 1250.   ,  797.   ,  998.   ,  659.9  ,  734.9  ,
        930.   ,  749.9  , 2295.   ,  824.9  ,  895.   ,  292.   ,
        899.   ,  350.   , 2250.   ,  804.   ,  204.   ,  239.5  ,
        695.   ,  380.   ,  750.   ,  510.   , 1025.   ,  199.99 ,
        169.5  , 1500.   , 2399.   , 2495.   ,  127.969,  664.9  ,
        679.9  ,  145.886,  659.9  ,  215.   ,  600.   ,  529.   ,
        489.9  ,  150.09 ,  118.671])

In [49]:
from sklearn.metrics import mean_squared_error

In [50]:
mean_squared_error(Y_test, Y_pred)

434123.85202188615